const api=(new URLSearchParams(location.search).get('api')||`${location.protocol}//${location.hostname}:8080`).replace(/\/$/,'');
const $=s=>document.querySelector(s);
async function req(path,opt={}){const r=await fetch(api+path,opt),p=await r.json().catch(()=>({}));if(!r.ok)throw Error(p.error||`HTTP ${r.status}`);return p}
function msg(t,ok=false){const el=$('#maintenance-result');el.textContent=t;el.style.color=ok?'#079b61':'#68778e'}
function val(id){return $('#'+id)?.value?.trim()||''}
async function load(){try{const s=await req('/api/device/overview'),i=s.identity||{},n=s.network||{},st=s.storage||{};$('#device-name').value=i.device_name||'';$('#device-id').value=i.device_id||'';$('#station-id').value=i.station_id||'';$('#device-host').value=i.hostname||'';$('#net-mode').value=n.mode||'dhcp';$('#net-interface').value=n.interface||'';$('#static-ip').value=n.static_ip||'';$('#netmask').value=n.netmask||'';$('#gateway').value=n.gateway||'';$('#dns').value=n.dns||'';$('#wifi-ssid').value=n.wifi_ssid||'';$('#net-ip').textContent=n.ip||'--';$('#net-mac').textContent=n.mac||'--';$('#link-speed').textContent=n.link_speed||'--';$('#storage-used').textContent=st.used_gb??'--';$('#storage-total').textContent=st.total_gb??'--';$('#service-status').textContent=s.services?.backend||'--';$('#alarm-status').textContent=s.peripherals?.alarm_light?.connected?'已连接':'未连接';$('#device-status').textContent='● 设备在线'}catch(e){$('#device-status').textContent='● 无法连接';$('#device-status').style.color='#d33'}}
$('#device-host').disabled=false;
$('#save-identity').onclick=async()=>{const button=$('#save-identity');const data={device_name:val('device-name'),device_id:val('device-id'),station_id:val('station-id'),hostname:val('device-host')};if(!data.device_name||!data.device_id||!data.hostname){msg('设备名称、设备编号和主机名不能为空');return}button.disabled=true;button.textContent='保存中…';msg('正在保存身份信息…');try{const p=await req('/api/device/identity',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const i=p.identity||data;$('#device-name').value=i.device_name;$('#device-id').value=i.device_id;$('#station-id').value=i.station_id;$('#device-host').value=i.hostname;msg('身份已保存，工作台将在 3 秒内同步',true);localStorage.setItem('device-identity-updated',String(Date.now()));}catch(e){msg('保存失败：'+e.message)}finally{button.disabled=false;button.textContent='保存身份'}};
async function action(path,body={},confirmText){if(confirmText&&!confirm(confirmText))return;try{const p=await req(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});msg(p.message||'操作完成',true);load()}catch(e){msg(e.message)}}
$('#save-network').onclick=async()=>{const mode=val('net-mode');if(mode==='static'&&!val('static-ip'))return msg('静态 IP 模式必须填写 IP 地址');if(!confirm('应用网络配置后 IP 可能变化，浏览器将暂时断开，是否继续？'))return;try{await req('/api/network',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,interface:val('net-interface'),static_ip:val('static-ip'),netmask:val('netmask'),gateway:val('gateway'),dns:val('dns'),wifi_ssid:val('wifi-ssid')})});msg('网络配置已保存',true);await load()}catch(e){msg('网络配置保存失败：'+e.message)}};
$('#network-test').onclick=async()=>{const b=$('#network-test');b.disabled=true;b.textContent='测试中…';msg('正在测试网络连通性…');try{const p=await req('/api/network/test',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});msg(`${p.message||'测试完成'}，延时：${Number.isFinite(Number(p.latency_ms))?p.latency_ms+' ms':'--'}`,Boolean(p.ok));}catch(e){msg('网络测试失败：'+e.message)}finally{b.disabled=false;b.textContent='网络连通性测试'}};$('#alarm-test').onclick=()=>action('/api/peripherals/alarm-light/test');$('#backup').onclick=()=>action('/api/config/backup');$('#restore').onclick=()=>action('/api/config/restore',{},'确认恢复最近一次配置备份？');$('#clear-logs').onclick=()=>action('/api/system/clear-logs',{},'确认清理缓存和日志？');$('#factory-reset').onclick=()=>{const password=prompt('请输入设备管理员密码（开发环境：admin）');if(password!=='admin')return msg('管理员密码错误');action('/api/system/factory-reset',{confirm:true,password},'恢复出厂设置会清除设备配置，确定继续？')};document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.body.classList.toggle('wifi-tab',t.dataset.tab==='wifi')});load();setInterval(load,5000);
$('#backup').onclick=async()=>{const b=$('#backup');b.disabled=true;b.textContent='生成中…';msg('正在生成配置备份…');try{const p=await req('/api/config/backup',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const filename=(p.file||'').split('/').pop();if(!filename)throw Error('后端未返回备份文件名');const response=await fetch(api+'/api/config/backups/'+encodeURIComponent(filename));if(!response.ok)throw Error('备份下载失败');const blob=await response.blob();const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=filename;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(link.href),1000);msg(`备份已下载：${filename}（设备路径：${p.file}）`,true)}catch(e){msg('备份导出失败：'+e.message)}finally{b.disabled=false;b.textContent='导出配置备份'}};
